{{- range .Values.secretStores }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}
